language: python
sudo: false
branches:
    only:
      - master
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r django_requirements.txt
  - pip install codecov
script:
  - tox
  - make doc quality
after_success:
  - codecov
